### ISSUE TITLE
Show/hide exception is not working

### ISSUE THREAD

**Issue by keita43a** [atusy/minidown#12]
Hi atusy,

Thank you for the great package. I am enjoying this light-weight HTML designs with handy settings of code foldings. 

I ran into an issue that might be a bug. 
I was going to use the exception function to hide my output by using "output.class = 'hide'" in the chunk option, but it did not work. 

So I copied and ran your code from the demo below, but both sources are shown. 

![スクリーンショット 2020-06-07 14 36 24](https://user-images.githubusercontent.com/9604858/83968846-4903c500-a8cc-11ea-8395-2bd1ba0d3ea7.png)

<img width="742" alt="スクリーンショット 2020-06-07 14 02 56" src="https://user-images.githubusercontent.com/9604858/83968479-e5789800-a8c9-11ea-8e28-a7e711bd08fd.png">

Also, I made a toy example attached (the zip file include a Rmd and html). 
The issue in addition to showing source exception is that the figure is always shown regardless of the chunk option and code folding option. Is there any way I can hide the figure?

[minidown_test.zip](https://github.com/atusy/minidown/files/4742088/minidown_test.zip)

Thanks!

Keita

**Comment by atusy** [comment]
@keita43a 

Thank you for the report.

Please use `class.source` instead of `source.class` (cf. https://yihui.org/knitr/options/#text-results).
It is my mistake on the documentation, and fixed now.

Folding figures have not been implemented yet.
I do have a plan.
