### ISSUE TITLE
Interaction with pandoc at CRAN on Windows

### ISSUE THREAD

**Issue by eddelbuettel** [atusy/minidown#18]
So I tried to submit a first package using minidown and it came back with

```
Flavor: r-devel-windows-ix86+x86_64
Check: re-building of vignette outputs, Result: WARNING
  Error(s) in re-building vignettes:
  --- re-building 'motivation.Rmd' using rmarkdown
  pandoc.exe: unrecognized option `--lua-filter'
  unrecognized option `--lua-filter'
  unrecognized option `--lua-filter'
  Try pandoc.exe --help for more information.
  Error: processing vignette 'motivation.Rmd' failed with diagnostics:
  pandoc document conversion failed with error 2
  --- failed re-building 'motivation.Rmd'
```

Is that us, _i.e._ is `minidown` calling in a non-standard way, or is this CRAN having an outdated `pandoc` binary on Windows?

Do you know?  (And by all means please feel free to close if you think that is outside the scope of your package...)

**Comment by atusy** [comment]
Thanks for the report.

> is this CRAN having an outdated pandoc binary on Windows?

That is what I think.
`--lua-filter` is supported since Pandoc 2.0.

**Comment by eddelbuettel** [comment]
Yes, I came to the same conclusion. I also asked Uwe in a calm private email days ago about updating ... and have not heard back.

So I gave up and converted the vignette to pdf.  A pity.  

But no issue per se in `minidown` as you have your SystemRequirement: set correctly.  Sadly just limits use of `minidown` for other vignettes. So I'll close this.

**Comment by eddelbuettel** [comment]
One thing you could consider is to react like `rmarkdown` as Duncan Murdoch [suggested](https://stat.ethz.ch/pipermail/r-package-devel/2020q3/006052.html) (plus [follow-up](https://stat.ethz.ch/pipermail/r-package-devel/2020q3/006054.html)) in the thread I had started on this on the [r-package-devel mailing list](https://stat.ethz.ch/mailman/listinfo/r-package-devel).  Simply by not erroring out under Windows you *would* enable use at CRAN.  Windows is not used to build the vignette, all we need is not to error.

**Comment by atusy** [comment]
Thanks for the suggestion. Should work better by 24e89dc. I'll plan to submit updated version in November. (I wanna submit **importas** package in October)

**Comment by eddelbuettel** [comment]
I really _really_ *really* liked the vignette I had based on your package and style "water".   I would love to use it in several vignettes.

For that it has to be on CRAN so that win-builder uses it.  A git commit buy me nothing -- I can already use your package _locally_ but not in a package pipeline.

Can I twist your arm to upload sooner?

**Comment by atusy** [comment]
I'm so happy to hear it.
Alright. The initial release is 5 month ago. That's an enough interval. I'll run rhub checks before I go sleep, and make a release as soon as possible.
Good night!!

**Comment by eddelbuettel** [comment]
Thank you, [CRANberries](https://twitter.com/CRANberriesFeed/status/1311350639327358976) just told me it is already on! 

I'll wait a few days for the win-builder to produce the Windows binary and then try my upload.

**Comment by eddelbuettel** [comment]
You have your first reverse Suggests:  https://cran.r-project.org/web/packages/minidown/index.html   :smiley: 

There will be more.  This one was easiest becomes it is a Linux + macOS only package.

**Comment by atusy** [comment]
Hooray!! Thanks a lot!!

**Comment by eddelbuettel** [comment]
And I already told CRAN about the *substantial* size reduction.  The package has a little bit more code (short files) but look at the size difference simply because of the vignette switch:

```sh
edd@rob:~/git/littler(master)$ ls -lh ~/cranberries/sources/littler_0.3.1[12]*
-rw-rw-r-- 1 edd edd 641K Jun 26 11:02 /home/edd/cranberries/sources/littler_0.3.11.tar.gz
-rw-rw-r-- 1 edd edd 116K Oct  7 08:02 /home/edd/cranberries/sources/littler_0.3.12.tar.gz
edd@rob:~/git/littler(master)$ 
```

Half a megabyte _compressed_.

**Comment by atusy** [comment]
Wow! That's so cool!!

**Comment by eddelbuettel** [comment]
`water` is fabulous.  Thanks so much for providing it.

I don't use too much else yet from your framework (and may never do, I tend to keep my vignettes simple) but the fight against bloat is worse it.

(And I still need your hint in #17 which did not make it into 0.0.2.  Maybe in 0.0.3 ?)

**Comment by atusy** [comment]
Yeah, #17 will be a milestone of 0.0.3.

**Comment by eddelbuettel** [comment]
With all due respect I did not ask you to retweet the above *quick* comment *verbatim*.  Not cool.

Could you pretty please delete the tweet and reformat one with your content?  Feel free to refer to the files, don;t use my listing.

**Comment by atusy** [comment]
Sorry about that. Deleted.

**Comment by eddelbuettel** [comment]
Two things I forgot "earlier": 

- We may want to take a look at your documentation; it took me a moment to find out how to do a minimal vignette with `water`. Your focus seems to be on code folding, and that is cool, but there are other use cases too.  Maybe another gooal for 0.0.3?

- Turns out that the warning you issue about `pandoc` is harmless because vignette processing already suppresses warnings on the R side (presumably because some much "noise" can come from the LaTeX side).  So that is no concern; I was overly worried.

**Comment by eddelbuettel** [comment]
And the next (initial) one on CRAN using minidown bringing down reverse Suggests to two :)

Another one in the works, I'll just wait the usual month between package updates.

**Comment by eddelbuettel** [comment]
And another one bringing it to four :)

![image](https://user-images.githubusercontent.com/673121/97058424-6b347180-1553-11eb-9cd0-f2176612cbeb.png)

**Comment by atusy** [comment]
COOL!!! Thanks a lot!!
