### ISSUE TITLE
Feature request: Collapse option

### ISSUE THREAD

**Issue by eddelbuettel** [atusy/minidown#22]
`minidown` is coming in handy and I already have two packages converted to it, plus one new one with its vignette.

One option I like, but which you may not like given all the folding option, is to enable `collapse=TRUE` at the `knitr` level.  That way both the computed _input_ and the (usually displayed) _output_ are in the same chunk.  I find this visually more pleasing and less distracting and the sequence  text, one code+result chunk, text, ... seems like a more natural flow to me.  We use this for example a lot in the `pinp` vignettes (in pdf) that are used across a lot of Rcpp documentation (and a few other packages of mine).

I looked into adding it but as your setup is a little different I thought I'd let you look at it first :)   

How would feel about such an option?

**Comment by atusy** [comment]
I'm the one who loves `collapse = TRUE`, too!
Yet, I think it is easy enough for users to set `collapse = TRUE` by themselves.

```r
knitr::opts_chunk$set(collapse = TRUE)
```

If I set `collapse = TRUE` as default, users who want `code_folding` will have to set `collapse = FALSE` at the same time.
I think this is complex...

**Comment by eddelbuettel** [comment]
Confirming that just `knitr::opts_chunk$set(collapse = TRUE)` works, and now I feel foolish as I am pretty sure I tried that too.  But as you hint it is complex so maybe presence of one of the other options undid it.

**Comment by atusy** [comment]
Great that you solved the problem :)

**Comment by eddelbuettel** [comment]
I am not sure I would call it "solved".  To be a first-class member of the `minidown` functionality I should it should be set-able in the YAML header but I will leave that to you.

**Comment by eddelbuettel** [comment]
I was also wrong.  It does not work in a document -- (I was rushing earlier).  

If `knitr::opts_chunk$set(collapse = TRUE)` works for you could you please show a complete (minimal) document for it?

**Comment by atusy** [comment]
i haven't tried. Let me see...

**Comment by eddelbuettel** [comment]
(I kept hacking away at this, not luck.  

Case in point in the old / simple / basic / not so pretty single vignette in [package digest](https://github.com/eddelbuettel/digest/blob/master/vignettes/sha1.Rmd).  Help would be most welcome :)

**Comment by atusy** [comment]
Okay, I figured out.
This should help.

````
---
title: "Untitled"
output:
  minidown::mini_document: null
---

```{r}
knitr::opts_chunk$set(
  collapse = TRUE,
  class.output = NULL,
  class.message = NULL,
  class.warning = NULL,
  class.error = NULL
)
```


```{r}
str(1)
```
````

It seems specifying classes conflict with `collapse`.
I think `collapse` should have priority, and thus I guess we should patch knitr.

Related issue: https://github.com/yihui/knitr/issues/1893

**Comment by cderv** [comment]
@atusy you could also make it a priority in **minidown** using an option hook

````r
---
title: "Untitled"
output:
  minidown::mini_document: null
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE
)
knitr::opts_hooks$set(collapse = function(options) {
  if (isTRUE(options$collapse)) {
    opts <- paste("class", c("output", "warning", "message", "error"), sep = ".")
    options[opts] <- NULL
  }
  options
})
```

```{r}
str(1)
```
````

if you define `collapse` as an option in the yaml field for `mini_document` format, I guess you could activate that hook if `collapse: TRUE` is set.

**Comment by eddelbuettel** [comment]
Nice(r).  

The `digest` vignette I started with had multiple code-output-code-output-code-output segments in the first code snippet, that still becomes three 'blocks' of code-output.  That may be all we can do...

**Comment by cderv** [comment]
@eddelbuettel I think you need to use the current `knitr` dev version which have the fix of the issue mentioned by @atusy above : https://github.com/yihui/knitr/issues/1893

I think yours is the same and the three blocks should become one if I am understanding correctly. If not, then there could still be an issue to fix in knitr I guess.

**Comment by eddelbuettel** [comment]
Ok, in that case I can probably wait for the release.  Dev versions buy me nothing as they are not on CRAN etc.  But it is a relatively minor never finished vignette (within `digest`) that does not have the greatest importance.  Just looking at other vignettes of mine I could make smaller yet nicer -- I really like `water.css` for vignettes.

**Comment by cderv** [comment]
> Ok, in that case I can probably wait for the release. Dev versions buy me nothing as they are not on CRAN etc. 

Yes I know. Last release was end of September,so next should be by the end of this month, or early November.

**Comment by atusy** [comment]
@cderv 
Thanks for the workaround and for opening the issue on **knitr**. Yes, the hook is the way. I'll try make some time this weekend.

**Comment by atusy** [comment]
Solved the issue by re-implementing the code folding feature.

**Comment by eddelbuettel** [comment]
Thanks -- I used the workaround for now and have the third package using `minidown` at CRAN now.

**Comment by cderv** [comment]
@atusy `collapse` option has now priority in last dev version of **knitr**

**Comment by eddelbuettel** [comment]
@cderv @atusy Can I ask you a quick question?   This may be a silly question as I seem to have forgotten some Sweave / Knitr basics.  In essence, `collpase` is lovely because it allow us to fuse

    code
    code
    code generating output
    output

into one "chunk" which is nice.  In one vignette (and possibly some other place) I have some (contributed) code that does several of those collated:

    code
    code
    code generating output
    output
    code
    code
    code generating output
    output

Is it possible to 'multi-collapse' all of that into a single chunk?  I can no longer remember if that ever worked, and if so only for latex or html output.   I think it would be nice to alter the flow of text and code with such a chunk containing multiple code snippets.  Is that possible after all or am I chasing a mirage here?

**Comment by atusy** [comment]
@cderv Thanks. I removed the corresponding hacks from minidown.

@eddelbuettel 
It should work as expected. Note that you may also want `fig.show='hold'`.
Try:

````
```{r, collapse=TRUE}
1
2
```

```{r, collapse=TRUE, fig.show='hold'}
plot(1)
plot(2)
```
````

**Comment by eddelbuettel** [comment]
Not sure I follow / I tried just setting `collapse` globally.  

If you look at the (now updated) `digest` (work in progress) vignette [here](https://cloud.r-project.org/web/packages/digest/vignettes/sha1.html) you see (and I cheat with a screenshot) 

![image](https://user-images.githubusercontent.com/673121/96388771-a9efb380-1170-11eb-939e-8f2be5356f35.png)

How could I make those three framed boxen just one?  It is the same with what you suggested -- printing `1` followed by `2` shows 'two boxed' results.  

(But as I said, I may actually be asking for something that does not exist (easily) so ... no worries in telling me :)  )

**Comment by atusy** [comment]
I meant to use `opts_chunk$set` with knitr on the development version.
It seems you also need `class.source = NULL` if you want CRAN version of knitr.
Note that `code_folding` won't work in this case.

```
knitr::opts_chunk$set(collapse = TRUE,
                      class.source = NULL,
                      class.output = NULL,
                      class.message = NULL,
                      class.warning = NULL,
                      class.error = NULL)
```

**Comment by eddelbuettel** [comment]
Just updated to your master -- that is _awesome_.  Lovely new and improved look and feel.
