### ISSUE TITLE
New minimal style?

### ISSUE THREAD

**Issue by eddelbuettel** [atusy/minidown#25]
Just came across this which is actively developed:  https://github.com/susam/spcss

Demo:  https://susam.github.io/spcss/

Not sure if you have time. I bookmarked it, and `water` remains golden but this looks good too...

**Comment by atusy** [comment]
Thanks!! I'll take a look!!

**Comment by eddelbuettel** [comment]
It looks pretty plain and simple (with maybe the code snippet 'too simple').   OTOH you also added other bells and whistles.  If it first, great -- if not no worries!
