### ISSUE TITLE
Over-eager actions

### ISSUE THREAD

**Issue by eddelbuettel** [atusy/minidown#39]
I updated my (mostly inactive now) fork to your master and promptly got "punished" with a failing action:
https://github.com/eddelbuettel/minidown/runs/1717199159?check_suite_focus=true

From a glance it looks like it wants to deploy. You may want to ensure such actions requiring your id and token only run as you.  No a big deal as a fork is a fork but I thought I'd mention it.  Feel free to close it.

**Comment by atusy** [comment]
Thanks for the notice.
I am not well experienced with GitHub Actions.
I appreciate if you can show some resource on how to 

> ensure such actions requiring your id and token only run as you

or you can open a PR.
Thanks!

**Comment by eddelbuettel** [comment]
I have no idea -- personally I am more prudent and I guess I would never attempt anything as ambitious as pushing to remote resources which are dependent on who is running the hob.  But hey if it works for you ...

This issue ticket was mostly just informing you that given how things are set up other users will get a failed run.

**Comment by atusy** [comment]
Okay, I'll try your suggestion or inspect **pkgdown**'s way.
The basic idea of my action comes from `pkgdown::deploy_to_branch`, and I remember it implements the more robust approach.

Thank you again.
I understand it is very annoying for others facing such failures.

**Comment by atusy** [comment]
This issue should be fixed by the above commits.
Feel free to reopen if you find any inconvenience.

**Comment by eddelbuettel** [comment]
Looks good!  I think I needed a similar if/else recently to run coverage only in the main element of a matrix and I think there is a more global conditional one level up:

```
      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./run.sh coverage
```

But no need to change it, and big thanks for fixing this too!
