### ISSUE TITLE
TOC highlighting doesn't work with non-ASCII headings

### ISSUE THREAD

**Issue by svraka** [atusy/minidown#58]
See [this gist](https://gist.github.com/svraka/d08580e15e2c2c49c6048030ddcb2bd6) for a reprex, and for previews [with ASCII](https://gistcdn.githack.com/svraka/d08580e15e2c2c49c6048030ddcb2bd6/raw/1ab1a0de9709fc119c9603d462ae815a310da8b8/minidown-ascii.html) and [with Unicode](https://gistcdn.githack.com/svraka/d08580e15e2c2c49c6048030ddcb2bd6/raw/1ab1a0de9709fc119c9603d462ae815a310da8b8/minidown-unicode.html). I'm using the latest HEAD of minidown, with the latest CRAN dependencies and latest Pandoc.

**Comment by atusy** [comment]
Thank you for the report, and sorry for the late response.
I reproduced the issue.
I'll take a look for the fix.

**Comment by atusy** [comment]
Should be fixed now.

I was trying to find link targets with `hash`, but it encodes non-ASCII characters to ASCII.
I alternatively applied `attributes.href.value`, which extracts the raw one.

https://github.com/atusy/minidown/commit/865006238253b8f2f2e8d1958ce3f6c0df36f6d7#diff-ddca43bdcccf8a8c1ab4e10c06ffd5aaef7f516b757dfccb5389bc04587b8cd8L16-R16
