### ISSUE TITLE
Suggest or Import mime for download_rmd_button()

### ISSUE THREAD

**Issue by yihui** [atusy/minidown#59]
Due to https://github.com/yihui/knitr/pull/2020, **mime** will no longer be an indirect dependency of **knitr** (`knitr -> markdown -> mime`). You will have to declare the dependency on **mime** explicitly in DESCRIPTION (either `Imports` or `Suggests` should be fine, but I'd recommend the former in this case). Thanks!

**Comment by atusy** [comment]
Thank you for the suggestion.
As far as I understand, **minidown** depends on **mime** via `xfun::embed_file`, right?
Does it still require **minidown** declare the dependency?

https://github.com/atusy/minidown/blob/4b14ed11ad5a220334effec44c29f48a130d5130/R/download-rmd.R#L45

**Comment by yihui** [comment]
Yes, because **xfun** only Suggests **markdown**. Previously you can assume **mime** is available during `R CMD check --as-cran` because you have suggested **knitr**. Now this assumption is no longer true.

**Comment by atusy** [comment]
I see `xfun` also suggests **mime**, but does not imports.
I'll import **mime** on **minidown**.
Thanks again.

https://github.com/yihui/xfun/blob/730d16c89996d0cd1bfa6a4038ef13fad47ae5ea/DESCRIPTION#L22-L23

**Comment by atusy** [comment]
@yihui 

JFYI, CRAN seems to have changed their decisions and is now raising notes even with `if (FALSE) mime::guess_type`.

https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/minidown-00check.html

**Comment by yihui** [comment]
Thanks for letting me know! I'd use `guess_type <- function(...) mime::guess_type(...)` just in case you or someone else would actually call this function somewhere in the future.
