### ISSUE TITLE
GT Package- row_striping=FALSE does not work with minidown

### ISSUE THREAD

**Issue by JUJABuddy** [atusy/minidown#70]
Using the same code:
**cars %>% gt() %>%gt::opt_row_striping(row_striping=FALSE)**

with output:
   minidown::mini_document: it still applies the stripes: 
![image](https://user-images.githubusercontent.com/91881429/140062927-d50ecc9e-6078-4b04-a4e0-5c7677b9c6bc.png)

while with output: html_document it does not apply the stripes- as expected: 
![image](https://user-images.githubusercontent.com/91881429/140063009-17d481c1-2663-437e-9c62-86f03397ed67.png)

**Comment by atusy** [comment]
Thank you for using the **minidown** package.
Unfortunately, the issue is not reproducible.

````
---
output: minidown::mini_document
---

```{r}
library(magrittr)
cars %>% gt::gt() %>%gt::opt_row_striping(row_striping=FALSE)
```
````

![image](https://user-images.githubusercontent.com/30277794/140073049-a27e273f-7ad1-404f-aaf4-ca0f26ab07a1.png)

**Comment by JUJABuddy** [comment]
Sorry I didnt specify it enough. This happens when using: 
   minidown::mini_document:
     framework: water
     theme: light

**Comment by atusy** [comment]
Ok, now I reproduced, but this is not a bug in **minidown**.

I suggest you open issue in https://github.com/rstudio/gt so to add a CSS rule like below when `gt::opt_row_striping(row_striping=FALSE)` is set.

```css
.gt_table tbody tr {
    background-color: unset;
}
```

In a meanwhile, you can workaround the issue by adding the above CSS rule by yourself.

<details><summary>Example of workaround</summary>

````
---
output:
  minidown::mini_document:
    framework: water
    self_contained: false
---

```{css}
.gt_table tbody tr {
    background-color: unset;
}
```

```{r}
library(magrittr)
cars %>% gt::gt() %>%gt::opt_row_striping(row_striping=FALSE)
```
````

</details>
